### ISSUE TITLE
Conditional Insert or Update question.

### ISSUE THREAD

**Issue by teebu** [awspilot/dynamodb-oop#16]
How would I do it? Does this support that?

**Comment by teebu** [comment]
For example:

I have two date fields:

createdAt
updatedAt

How would I go about doing that?

**Comment by databank** [comment]
Hi,

conditional updates are somehow used internally by this library but undocumented,

insert() = PUT if partition (optionally sort) key do not exist, fail otherwise
insert_or_update() = unconditional ADD 
insert_or_replace() = unconditional PUT

I'm preparing something like:
```
     DynamoDB
          .table(tableName)
          .where('hash').eq('hashkey')
          .where('range').eq('rangekey')
          .if('number').gt(0)
          .if('active').eq(true)
          .update({
               number: DynamoDB.inc(-1), // decrement until its 0 if 'active'
          }, function( err, data ) {})
```

although this does not seem to fit you as doing the following will fail with "conditional update failed"
when createdAt exists
```
     .if('createdAt').undefined()
```

I`ll think of something and get back to you

-adrian

**Comment by teebu** [comment]
any update on this?

**Comment by M1chaelTran** [comment]
I'm trying to do the exact same things as @teebu 
updates on this would be nice after 2 years?

**Comment by adrianpraja** [comment]
@M1chaelTran , @teebu 


From the current docs for [updateItem > updateExpression
](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-UpdateExpression)
it seems AWS does not allow  conditional update at attribute level



You can either:

- do a ```.get()``` and then ```.insert()``` if item does not exit or ```.update()```otherwise

or

- do an ```.insert()``` , if error is ```ConditionalCheckFailedException```  do an ```.update()```

or

- do an ```update()```,  if error is ```ConditionalCheckFailedException```  do an ```.insert()```

Answer is: you can;t do this using one call,  I'm closing this issue
