### ISSUE TITLE
Cannot  use region provided in config.json

### ISSUE THREAD

**Issue by ikekykay** [awspilot/dynamodb-oop#36]
Hi, 

I am  my config.json contains region.  I am using 

// Load the AWS SDK for Node.js
var AWS = require('aws-sdk');
// Load credentials and set region from JSON file
AWS.config.loadFromPath('config/config.json');

//AWS.config.update({region: 'us-east-1'});

var $db = new AWS.DynamoDB();
var DynamoDB = require('@awspilot/dynamodb')($db);

But I still get 
ConfigError: Missing region in config   error . 

Config.json looks like 
{ "accessKeyId": "XXXXXXXXXX", 
"secretAccessKey": "##############", 
"region": "us-east-1" 
}

**Comment by adrianpraja** [comment]
It seems that DynamoDB / dynamodb-doc had similar issues in the past
https://github.com/awslabs/dynamodb-document-js-sdk/issues/16

I see that `$db instanceof AWS.DynamoDB` returns false
because @awspilot/dynamodb internally uses another instance of AWS.DynamoDB

I will find a fix thanks for reporting

**Comment by adrianpraja** [comment]
I've pushed `@awspilot/dynamodb:1.0.9` that has this fixed

Please re-open this issue if you still see the error

Thanks,
